import { createWriteStream } from 'fs';
import { createRandomDataStream, testChannels } from '../data/utils';
import { MlgWriter } from '../../src/converters/mlg/mlg.writer';

const mlvlg = new MlgWriter({
  channels: testChannels,
  description: 'Generated by racing-data-converter',
});

const data = createRandomDataStream();
const out = createWriteStream('./test/samples/out/test-mlg' + mlvlg.extension);

mlvlg.createStream(data).pipe(out);
